default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.secrets.host %>
  port: <%= Rails.application.secrets.port %>
  database: <%= Rails.application.secrets.database %>
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
